
project_id = "wxlamjmnqefpjdewxbyz"

[functions.google-oauth-initiate]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.create-meet-lecture]
verify_jwt = true

[functions.save-google-tokens]
verify_jwt = true

[functions.update-meet-lecture]
verify_jwt = true

[functions.cancel-meet-lecture]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false
