// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxlamjmnqefpjdewxbyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bGFtam1ucWVmcGpkZXd4Ynl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTk5NTMsImV4cCI6MjA2NDUzNTk1M30.wa79dcXyBaEG9DymgxN8eiaEdEDDJLbPPz81YwE3oHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});